version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: "latest"
  build:
    commands:
      - echo "Installing..."
      - npm install
      - echo "Building..."
      - npm --version
      - node -v
      - npm run build
  post_build:
    commands:
      - echo "Build completed"
      - echo "Uploading build to S3 Bucket"
      - aws s3 sync ./out s3://frontend-photoalbum-2 --delete

artifacts:
  files:
    - 'out/*'
  base-directory: 'out/'
  discard-paths: no


# cache:
#   paths:
#     - 'node_modules/*/'