version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: "latest"
  pre_build:
    commands:
      - npm install -g npm stable
      # - npm install -g node
  build:
    commands:
      - echo "Building..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed"
      - echo "Uploading build to S3 Bucket"
      - aws s3 sync ./build s3://frontend-photoalbum-2 --delete

# artifacts:
#   files:
#     - '**/*'
#   base-directory: 'build/'
#   discard-paths: no


# cache:
#   paths:
#     - 'node_modules/*/'